name: Unused Dependencies

on:
  pull_request:
    branches: ["main"]

jobs:
  detect-unused-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - name: Machete
        uses: bnjbvr/cargo-machete@6b17ed8200a096fda2a7e1a98940f90c9ef36d2b # main
